name 'dsecond'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dsecond'
long_description 'Installs/Configures dsecond'
version '1.15.0'
depends 'apt'
depends 'docker'
